behaviors:
  SoccerTwosHuman:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      gail:
        gamma: 0.99
        strength: 1.0
        encoding_size: 512
        learning_rate: 0.0003
        use_actions: true
        use_vail: true
        demo_path: Project/Assets/Demonstrations/Urciuoli_50000_steps.demo
    keep_checkpoints: 50
    checkpoint_interval: 500000
    max_steps: 25000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    #self_play:
      #save_steps: 50000
      #team_change: 200000
      #swap_steps: 2000
      #window: 10
      #play_against_latest_model_ratio: 0.5
      #initial_elo: 1200.0
