behaviors:
  SoccerTwosHuman:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      gail:
        gamma: 0.99
        strength: 1.0
        encoding_size: 128
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: Project/Assets/Demonstrations/Urciuoli_50000_steps.demo
    keep_checkpoints: 50
    checkpoint_interval: 500000
    max_steps: 25000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: true
    behavioral_cloning:
      demo_path: Project/Assets/Demonstrations/Urciuoli_50000_steps.demo
      steps: 50000
      strength: 0.5
      samples_per_update: 0